# coding:utf-8

# 英語フォント
require "pdf_font/courier"
require "pdf_font/courier_bold"
require "pdf_font/courier_bold_oblique"
require "pdf_font/courier_oblique"
require "pdf_font/helvetica"
require "pdf_font/helvetica_bold"
require "pdf_font/helvetica_bold_oblique"
require "pdf_font/helvetica_oblique"
require "pdf_font/symbol"
require "pdf_font/times_roman"
require "pdf_font/times_bold"
require "pdf_font/times_bold_italic"
require "pdf_font/times_italic"
require "pdf_font/zapf_dingbats"
# 日本語フォント
require "pdf_font/jp_default"
require "pdf_font/ms_gothic"
require "pdf_font/ms_gothic_bold"
require "pdf_font/ms_gothic_bold_italic"
require "pdf_font/ms_gothic_italic"
